### PR TITLE
Add contributor guidelines

### PR DESCRIPTION
**Pull request by replygirl**
- Fixed a typo
- Added how to join BSA team
- Added guides on rebasing for inside & outside collaborators

Part of #1

### CODE REVIEW

**Comment by replygirl** [comment]
😬 i dont want to close the issue i thought it would just associate

**Review by hangulu — DISMISSED** [review]
LGTM

**Comment by replygirl** [comment]
wait, i'm going to do this the right way and write this in contributing.md

**Comment by replygirl** [comment]
don't delete the branch anyone, i'll be reopening in a few minutes

**Comment by replygirl** [comment]
just moved contributor guidelines to the correct file

**Review by odbol — APPROVED** [review]

**Comment by 2ndline** [comment]
Thanks!

**Review by GrigoryGraborenko — APPROVED** [review]

**Review by sorcerix — APPROVED** [review]

**Review by geetotes — APPROVED** [review]

**Comment by replygirl** [comment]
Commit signing won't be accommodated by auto rebase, so I'm going to tweak the guidelines around signing soon

**Pull request merged**
