### PR TITLE
Restyle

### PR DESCRIPTION
**Pull request by GrigoryGraborenko**
Moved tour bar to be horizontal along the bottom, used flex box to space items nicely. Replaced downloaded SVG icons with material UI import icons so we can have icon consistency.

### CODE REVIEW

**Comment by odbol** [comment]
Thanks for starting this! One suggestion I have is I believe we agreed in a design meeting that we should also support the vertical dots for certain screen sizes/orientations.

So maybe instead of removing the CSS for the vertical dots, you could use some media queries in the CSS to determine if the screen is landscape vs portrait, and then position the dots horizontally or vertically, respectively.

**Comment by sorcerix** [comment]
@odbol makes sense, we are gonna add

**Comment by replygirl** [comment]
#### 📝Changed routes:


| [**/**](https://world-of-jackson-git-restyle.blacksocialists.now.sh/) |
|:-:|
|<a href="https://world-of-jackson-git-restyle.blacksocialists.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/jbPTBRWQeXEpOH7MQDyu6WGPhMc_.png">(view full size)</a> |







Commit d6f3988cf87fe89e71c0fe565c4e2454fa11e7cf (https://world-of-jackson-git-restyle.blacksocialists.now.sh).

**Comment by GrigoryGraborenko** [comment]
Done, we've added media queries now

**Comment by odbol** [comment]
Awesome, thanks! It seems like there's some unrelated commits now though... having to do with shaders and buildings and such. Maybe a rebase went wrong somewhere?

Also, I know we'll have more dots in the timeline in the final version, but maybe it might be better to center the dots in the screen, with a constant margin, instead of spread them out the entire width? They are very far apart when there's only three and it looks weird.

**Comment by odbol** [comment]
Also, on my screen at least, it looks like the forward/back arrows are transparent, which makes them blend in with the grey map. They should be white to ensure enough contrast to be accessible to people with low-vision.

**Comment by GrigoryGraborenko** [comment]
Yeah when I did the rebase, there was extra stuff in there, but I went through the features and everything still worked fine. Perhaps I started the branch when it was already behind?
About the styling - I agree the spacing is a little weird, it might be good to revisit it when we have more real content.

**Comment by sorcerix** [comment]
@odbol we had some discussions on the spacing and weren't sure what would be best, so we left it for now, we fixed the coloring for the arrow buttons though, but we will still need to make the color scheme as a whole accessible

**Review by sorcerix — APPROVED** [review]
good for now but there will be more work to be done in #31 and a new issue around the nav bar and modal

**Comment by odbol** [comment]
Hi all, it seems like you may have missed my comment about the regression in accessibility introduced by this change. Can you please address it?

Also in the future, it might be more respectful to wait for an approval from the person who took the time to review your code rather than approving it and merging it without giving them time to respond.

**Comment by sorcerix** [comment]
@odbol I approved it because it seemed like it was addressed. Now the arrow buttons are solid white when clicked. Do the buttons still blend in your screen? 

That said, you are right about it being better for us to wait for the other reviewers who commented  before approving, where possible. I definitely could have done better on that here, sorry about that.

**Comment by odbol** [comment]
Thanks for acknowledging that. 

As for the a11y, there were several things I was talking about, sorry if I didn't communicate that well enough:

1. The default state of the arrow *icons* themselves should be white, not the button *background*. (The arrows are still transparent which makes them hard to discern what they are since they blend with the grey background of the map shining through). 
  - I think it's ok to not use pure white as a button background since pure white is pretty harsh on the eyes. We can probably address the background color later though.

2. The labels of the buttons need to be text, not images. Reposting my original comment since I can't seem to link to it:

"Unfortunately this is not accessible. The buttons now lack the "Previous" and "Next" labels required for screen readers.

Generally it's better to use text as the button's content, and add images/icons via CSS when they are not actually crucial to the semantic meaning of the content (i.e. an "arrow icon" or "circle filled icon" has no semantic meaning... it's just graphic design which is purely visual. Purely visual things should stay in CSS)"

**Comment by GrigoryGraborenko** [comment]
Alright, will address in a new branch

**Pull request merged**
